openapi: 3.0.1
info:
  title: dev-loadWebsitesAws
  version: '2020-10-16T17:03:08Z'
servers:
  - url: 'https://totsjc3t30.execute-api.us-east-2.amazonaws.com/{basePath}'
    variables:
      basePath:
        default: dev
paths:
  /hello:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                website:
                  type: "array"
                  items:
                    type: string
            examples:
              1:
                summary: '1 example'
                value: 
                  website:
                  - "https://www.youtube.com/"
                  - "https://www.mama.com/"
              2:
                summary: '2 example'
                value: 
                  website:
                  - "https://www.google.com/"
                  - "https://www.facebook.com/"
              
      responses:
        '200':
          description: 200 response
          content: {}
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:938668680897:function:loadWebsitesAws-dev-hello/invocations'
        responses:
          default:
            statusCode: '200'
        requestTemplates:
          application/json: '{"website" : $input.json(''website'')}'
        passthroughBehavior: never
        httpMethod: POST
        type: aws
components: {}

